### ISSUE TITLE
Create module `sp_consensus_spartan`

### ISSUE THREAD

**Issue by rg3l3dr** [autonomys/spartan-node-template#11]
Abstract wrapper around some proof-of-space or proof-of-replication. This needs a better name. Perhaps this should be PoC and the higher level modules should be renamed?

## TODO

- [x] fork sp_consensus_vrf
- [ ] make generic over any PoC
- [x] refactor `spartan_codec` to match
- [x] update docs
- [x] update tests
