### ISSUE TITLE
Create module `sp_consenus_poc`

### ISSUE THREAD

**Issue by rg3l3dr** [autonomys/spartan-node-template#2]
Abstract Proof-of-Capacity consensus primitives. Forked from `sp_consensus_babe`.

## TODO

- [x] Initial setup
- [x] Replace VRF with `spartan-codec` (lib and digests)
- [x] Ensure `KEY_TYPE` is added to `sp_application_crypto::key_types`
- [x] Scrub out all Babe references
- [ ] Ensure that seal, signature, and proof are deduplicated
