### ISSUE TITLE
Create module `sc_consensus_poc`

### ISSUE THREAD

**Issue by rg3l3dr** [autonomys/spartan-node-template#3]
Client functionality for abstract Proof-of-Capacity consensus. Forked from `sc_consensus_babe`.

## TODO

- [x] initial setup
- [x] try to entirely remove `authorship.rs`
- [x] replace vrf with por
- [x] fix verification on `verification::check_primary_header()`
- [x] remove all notion of authorities
- [x] implement previous modifications for RPC
- [x] decide if farmer keys will be stored on the client at all
- [x] leave in force authoring (confirm)
- [x] scrub all babe references
- [x] fix all emojis and logging text
- [x] add fork disclaimer at top
- [x] uncomment and repair all tests
- [x] update readme
