### ISSUE TITLE
Create `pallet_spartan`

### ISSUE THREAD

**Issue by rg3l3dr** [autonomys/spartan-node-template#4]
Abstract Proof-of-Space consensus primitives. Based on fork of `pallet_babe`.

## TODO

- [x] initial setup
- [x] seek advice on which version of substrate to use ICW node-tempalte
- [x] seek advice on config version and migrations
- [x] remove all notions of sessions and validator counts
- [x] replace authority index with farmer-id from proof
- [x] replace vrf with por
- [x] re-introduce mock and adjust
- [x] re-introduce and adjust tests
- [x] update docs overall
