### ISSUE TITLE
Implement `spartan-client` using `substrate/bin/node-template`

### ISSUE THREAD

**Issue by rg3l3dr** [autonomys/spartan-node-template#6]
An implementation of `substrate-node-template` which runs under `pallet_spartan` consensus and connects to the `spartan-farmer`.

## TODO

- [x] remove grandpa finality
- [x] remove aura consensus
- [x] setup basic PoC consensus (no farmer)
- [x] connect to farmer over RPC
- [x] update the runtime
- [x] revise the chain spec
- [x] update docs
- [ ] update tests
- [x] final check all cargo.toml and licenses
